name : ci 
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

  repository_dispatch:
     types: [opened, deleted]
  
 
  check_run:
        types: [rerequested, requested_action]
jobs:
  deploy :
    runs-on: self-hosted 
    steps :
    - uses: actions/checkout@v2
      
    - name: run echo comande
      run:  echo bonjour >> /home/srv/adel.txt
    - name: update 
      run : sudo apt update -y 
    - name: install httpd 
      run : sudo apt install nginx -y 

