name : ci 
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build :
    runs-on: self-hosted 
    steps :
    - uses: actions/checkout@v2
      
    - name: run echo comande
      run:  echo bonjour >> /home/srv/adel.txt
    - name: update 
      run : apt udpate -y 
    - name: install httpd 
      run : sudo apt install nginx -y 

