name : ci 
on: [push]

jobs:
  build :
    runs-on: self-hosted 
    steps :
    - uses: actions/checkout@v2
      
    - name: run echo comande
      run:  echo bonjour >> /home/srv/adel.txt
    - name: update 
      run : apt udpate -y 
    - name: install httpd 
      run : sudo apt install nginx -y 

